# Generated by Django 3.2.3 on 2021-06-01 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_poll_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotesControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=16)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.poll')),
            ],
        ),
        migrations.AddConstraint(
            model_name='votescontrol',
            constraint=models.UniqueConstraint(fields=('session_id', 'poll'), name='Voto único'),
        ),
    ]
